name: Test Running

on:
  workflow_dispatch:

jobs:
  test-fount:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Run install script (Unix)
        if: runner.os != 'Windows'
        run: |
          git clone https://github.com/steve02081504/fount.git --depth 1 --single-branch --branch ${GITHUB_SHA}
          ./fount/path/fount.sh init

      - name: Run install script (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          git clone https://github.com/steve02081504/fount.git --depth 1 --single-branch --branch ${GITHUB_SHA}
          ./fount/path/fount.ps1 init

      - name: Run remove script (Unix)
        if: runner.os != 'Windows'
        run: ./fount/path/fount.sh remove

      - name: Run remove script (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: ./fount/path/fount.ps1 remove
