name: Test Running

on:
  workflow_dispatch:

jobs:
  test-fount:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Run install script (Unix)
        if: runner.os != 'Windows'
        run: |
          export FOUNT_DIR="./fount"
          curl -fsSL https://raw.githubusercontent.com/steve02081504/fount/refs/heads/master/src/runner/main.sh | bash -s init
          source "$HOME/.profile"

      - name: Run install script (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          $env:FOUNT_DIR = "./fount"
          $scriptContent = Invoke-RestMethod https://raw.githubusercontent.com/steve02081504/fount/refs/heads/master/src/runner/main.ps1
          Invoke-Expression "function fountInstaller { $scriptContent }"
          fountInstaller init

      - name: Run remove script (Unix)
        if: runner.os != 'Windows'
        run: ./fount/path/fount.sh remove

      - name: Run remove script (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: ./fount/path/fount.ps1 remove
